services:
  app:
    build: .
    container_name: torque-talk
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/torqueTalk
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: torqueTalk-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: torqueTalk
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: